name: Update

on:
  workflow_dispatch:
  
  push:
    branches:
      - main
    paths:
      - .github/workflows/Docker-Update.yaml
  
  schedule:
    - cron: 0 4 * * *

jobs:
  Update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0
          submodules: true
      - name: Update Exchange Rates
        run: |
          sudo apt-get install -y jq bc
          usdcny=`curl -sSL "http://api.currencylayer.com/live?access_key=6aa8e7d031256487cd884d292553d6e2&f" | jq '.quotes.USDCNY'`
          res=0`echo "scale=4;1/$usdcny" | bc`
          sed -i "s/dfFxrate = .*;/dfFxrate = $res;/g" modify/StripeController.php
      - name: Update Submodules
        run: git submodule foreach 'git fetch origin; git checkout $(git rev-parse --abbrev-ref HEAD); git reset --hard origin/$(git rev-parse --abbrev-ref HEAD); git submodule update --recursive; git clean -dfx'
      - name: Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Dockerfile
          skip_dirty_check: false
          commit_user_name: Action Bot
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: Action <actions@github.com>
